#! /bin/bash

function get_query
{
  read -p "次の選択肢から入力してください(Add Password/Get Password/Exit):" query 
}

function manager_exit
{
  echo Thank you!
  exit
}

function get_text(){
  text="$1"
  read -p "${text}名を入力してください:" string
  if [ -z ${string} ]; then
    echo "${text}名が空です。もう一度入力してください。"
    get_text "${text}"
  else
    echo ${string}
  fi
}

function add
{
  servis=$(get_text "サービス")
  user=$(get_text "ユーザー")
  password=$(get_text "パスワード")

  text=$(cat <<- EOS
  サービス名:$servis
  ユーザー名:$user
  パスワード:$password
EOS
)
  if [ -f temp.txt.gpg ]; then
    gpg -o temp.txt -d temp.txt.gpg
  fi
  echo ${text} >> temp.txt
  gpg -c temp.txt
  result=$?

  if [ ${result} -eq 0 ]; then
    echo パスワードの追加は成功しました。
  fi
  rm temp.txt
}

function retry
{
  echo 入力を間違えています。
  get_query
}

function get
{
  gpg -o temp.txt -d temp.txt.gpg
  servis_list=$(cat temp.txt)
  rm temp.txt
  read -p "サービス名を入力して下さい:" target
  read -r let1 let2 let3 <<< $(echo "$servis_list" | grep -w "サービス名:$target")

  if [ -n "$let1" ]; then
    echo $let1
    echo $let2
    echo $let3
  else
    echo "そのサービスは登録されていません。"
  fi
}

function main
{
case "$query" in
  Exit)
     manager_exit
     ;;
  "Add Password")
     add
     get_query
     main
     ;;
  "Get Password")
     get
     get_query
     main
     ;;
  *)
     retry
     main
     ;;
esac
}


echo パスワードマネージャーへようこそ!
get_query
main

